// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRAMS.Infraestructure.Data.SystemConfiguration;

#nullable disable

namespace PRAMS.Configuration.Migrations
{
    [DbContext(typeof(AppConfigDbContext))]
    [Migration("20240626060324_AddMenuItems")]
    partial class AddMenuItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", b =>
                {
                    b.Property<int>("MenuElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuElementId"));

                    b.Property<string>("Accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Controlador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuElementParentId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("MenuElementId");

                    b.ToTable("Adm_MenuElements");

                    b.HasData(
                        new
                        {
                            MenuElementId = 1,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Home",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8944),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-home",
                            Nombre = "Home",
                            Orden = 1
                        },
                        new
                        {
                            MenuElementId = 2,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "SystemConfiguration",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8947),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "System Configuration",
                            Orden = 2
                        },
                        new
                        {
                            MenuElementId = 3,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Parametros",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8949),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 2,
                            Nombre = "Parametros",
                            Orden = 1
                        },
                        new
                        {
                            MenuElementId = 4,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Categorias",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8950),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 2,
                            Nombre = "Categorias",
                            Orden = 2
                        },
                        new
                        {
                            MenuElementId = 5,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Ajustes",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8985),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "Ajustes",
                            Orden = 3
                        },
                        new
                        {
                            MenuElementId = 6,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Roles",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8987),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Roles",
                            Orden = 4
                        },
                        new
                        {
                            MenuElementId = 7,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Usuarios",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8989),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Usuarios",
                            Orden = 5
                        },
                        new
                        {
                            MenuElementId = 8,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Otro",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8990),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Otro",
                            Orden = 6
                        },
                        new
                        {
                            MenuElementId = 9,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "AgregarRol",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8992),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Agregar",
                            Orden = 7
                        },
                        new
                        {
                            MenuElementId = 10,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EditarRol",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8994),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Editar",
                            Orden = 8
                        },
                        new
                        {
                            MenuElementId = 11,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarRol",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8996),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Eliminar",
                            Orden = 9
                        },
                        new
                        {
                            MenuElementId = 12,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "AgregarUsuario",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8997),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Agregar",
                            Orden = 10
                        },
                        new
                        {
                            MenuElementId = 13,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EditarUsuario",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8999),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Editar",
                            Orden = 11
                        },
                        new
                        {
                            MenuElementId = 14,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(9001),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Eliminar",
                            Orden = 12
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuRole", b =>
                {
                    b.Property<int>("MenuRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuRoleId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuElementId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuRoleId");

                    b.HasIndex("MenuElementId");

                    b.ToTable("Adm_MenuRole");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro1_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro2_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro3_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro4_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro5_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro6_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro7_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro8_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro9_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Adm_ParametroCategoria");

                    b.HasData(
                        new
                        {
                            CategoriaID = 1,
                            Activo = true,
                            Categoria = "Clasificacion Empleados",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8684),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Clasificaciones"
                        },
                        new
                        {
                            CategoriaID = 2,
                            Activo = true,
                            Categoria = "Curso Aprobado",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8686),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 3,
                            Activo = false,
                            Categoria = "Curso Aprobado Demo",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8688),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 4,
                            Activo = true,
                            Categoria = "Tipo Impedimento",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8689),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 5,
                            Activo = true,
                            Categoria = "Tipo Nombramiento",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8691),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 6,
                            Activo = true,
                            Categoria = "Pueblos",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8692),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Def Pueblos con Dos Niveles de Filtros",
                            TX_Filtro1_Nombre = "Estado",
                            TX_Filtro2_Nombre = "Pais"
                        },
                        new
                        {
                            CategoriaID = 7,
                            Activo = true,
                            Categoria = "Categoria Licencias",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8694),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 8,
                            Activo = true,
                            Categoria = "Firmas",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8695),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "",
                            TX_Filtro1_Nombre = "Posición / Puesto"
                        },
                        new
                        {
                            CategoriaID = 9,
                            Activo = true,
                            Categoria = "Acciones",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8697),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 10,
                            Activo = true,
                            Categoria = "Genero",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8698),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 11,
                            Activo = true,
                            Categoria = "Region",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8700),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 12,
                            Activo = true,
                            Categoria = "Tipo Convocatoria",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8701),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 13,
                            Activo = true,
                            Categoria = "Dependencias",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8702),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 14,
                            Activo = false,
                            Categoria = "Dependencias2",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8704),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 15,
                            Activo = false,
                            Categoria = "Dependencias3",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8705),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 16,
                            Activo = true,
                            Categoria = "Entidades Municipio",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8707),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Def Municipios Tres Niveles Ejemplo",
                            TX_Filtro1_Nombre = "Region",
                            TX_Filtro2_Nombre = "Estado",
                            TX_Filtro3_Nombre = "Pais"
                        },
                        new
                        {
                            CategoriaID = 17,
                            Activo = true,
                            Categoria = "Cantidad Solicitudes",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8708),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 18,
                            Activo = false,
                            Categoria = "Cantidad Solicitudes2",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8710),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 19,
                            Activo = true,
                            Categoria = "Grados Academicos",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8711),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 20,
                            Activo = true,
                            Categoria = "Tipo de Documentos",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8747),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 21,
                            Activo = true,
                            Categoria = "Tipo Reportes",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8749),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 22,
                            Activo = true,
                            Categoria = "RolesReportes",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8750),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 23,
                            Activo = true,
                            Categoria = "RolesMenu",
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8752),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametrosSeleccion", b =>
                {
                    b.Property<int>("ParamterosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParamterosID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParamterosID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Adm_ParametrosSeleccion");

                    b.HasData(
                        new
                        {
                            ParamterosID = 1,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8831),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado"
                        },
                        new
                        {
                            ParamterosID = 2,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8833),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado Temporal"
                        },
                        new
                        {
                            ParamterosID = 3,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8835),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado Contratado"
                        },
                        new
                        {
                            ParamterosID = 4,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8836),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Carrera"
                        },
                        new
                        {
                            ParamterosID = 5,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8837),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Confianza"
                        },
                        new
                        {
                            ParamterosID = 6,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8838),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Base"
                        },
                        new
                        {
                            ParamterosID = 7,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8893),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "San Juan",
                            TX_Filtro1 = "Area Metro",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 8,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8895),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Carolina",
                            TX_Filtro1 = "Area Metro",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 9,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8896),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Arecibo",
                            TX_Filtro1 = "Area Norte",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 10,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8898),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Ponce",
                            TX_Filtro1 = "Area Sur",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 11,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8899),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Orange",
                            TX_Filtro1 = "Central",
                            TX_Filtro2 = "Florida",
                            TX_Filtro3 = "Estados Unidos"
                        },
                        new
                        {
                            ParamterosID = 12,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8901),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "New York City",
                            TX_Filtro1 = "Greater City",
                            TX_Filtro2 = "New York",
                            TX_Filtro3 = "Estados Unidos"
                        },
                        new
                        {
                            ParamterosID = 13,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8915),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Bernardo Acevedo González",
                            Parametro = "BAG",
                            TX_Filtro1 = "Analista de Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 14,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8916),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Carmín Rodríguez Negrón",
                            Parametro = "CRN",
                            TX_Filtro1 = "Directora"
                        },
                        new
                        {
                            ParamterosID = 15,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8918),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Jannette López Falcón",
                            Parametro = "JLF",
                            TX_Filtro1 = "Analista de Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 16,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8919),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Victor Maldonado Martínez",
                            Parametro = "VMM",
                            TX_Filtro1 = "Director"
                        },
                        new
                        {
                            ParamterosID = 17,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8921),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Juan Perez Rodriguez",
                            Parametro = "JPR",
                            TX_Filtro1 = "Analista ASUME"
                        },
                        new
                        {
                            ParamterosID = 18,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8922),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Nancy Calderon Alicea",
                            Parametro = "NCA",
                            TX_Filtro1 = "Especialista Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 19,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8923),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Gabriel Otero Valentin",
                            Parametro = "GOV",
                            TX_Filtro1 = "Analista ADSEF"
                        },
                        new
                        {
                            ParamterosID = 20,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8925),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Leslie Soto Matos",
                            Parametro = "LSM",
                            TX_Filtro1 = "Analista AMSCA"
                        },
                        new
                        {
                            ParamterosID = 21,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 6, 26, 0, 3, 23, 768, DateTimeKind.Local).AddTicks(8926),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Secretaria Gerencia",
                            Parametro = "SEC-GME",
                            TX_Filtro1 = "Administrador"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuRole", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", "AdmMenuElement")
                        .WithMany("AdmMenuRoles")
                        .HasForeignKey("MenuElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmMenuElement");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametrosSeleccion", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", "AdmParametroCategoria")
                        .WithMany("AdmParametrosSeleccions")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmParametroCategoria");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", b =>
                {
                    b.Navigation("AdmMenuRoles");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", b =>
                {
                    b.Navigation("AdmParametrosSeleccions");
                });
#pragma warning restore 612, 618
        }
    }
}
