// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRAMS.Infraestructure.Data.SystemConfiguration;

#nullable disable

namespace PRAMS.Configuration.Migrations
{
    [DbContext(typeof(AppConfigDbContext))]
    [Migration("20240820025814_InitConfigurationDB")]
    partial class InitConfigurationDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoFormulario", b =>
                {
                    b.Property<int>("FormularioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormularioId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Formulario")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("NivelCaso")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("OrdenFormulario")
                        .HasColumnType("int");

                    b.Property<string>("TXFiltro")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TX_Filtro");

                    b.Property<string>("TXFiltro2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TX_Filtro2");

                    b.Property<string>("TXFiltro3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TX_Filtro3");

                    b.Property<int>("TablaBase")
                        .HasMaxLength(75)
                        .HasColumnType("int");

                    b.Property<string>("TipoCaso")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("FormularioId");

                    b.ToTable("Adm_FlujosFormularios");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioEtapa", b =>
                {
                    b.Property<int>("FormularioEtapaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormularioEtapaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ColorEtapa")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("Completado")
                        .HasColumnType("bit");

                    b.Property<bool>("Concurrencia")
                        .HasColumnType("bit");

                    b.Property<int>("ConcurrenciaEtapa")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("FormularioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NombreEtapa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NotaEndId")
                        .HasColumnType("int");

                    b.Property<int?>("NotaStartId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenEtapa")
                        .HasColumnType("int");

                    b.Property<string>("TipoEtapa")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("FormularioEtapaId");

                    b.HasIndex("FormularioId");

                    b.HasIndex("NotaEndId");

                    b.HasIndex("NotaStartId");

                    b.ToTable("Adm_FlujoFormularioEtapas");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioEtapaAccion", b =>
                {
                    b.Property<int>("FormularioEtapaAccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormularioEtapaAccionId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Completado")
                        .HasColumnType("bit");

                    b.Property<bool>("Concurrencia")
                        .HasColumnType("bit");

                    b.Property<int>("ConcurrenciaAccionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("FormularioEtapaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NombreAccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrdenAccion")
                        .HasColumnType("int");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("TipoProceso")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("FormularioEtapaAccionId");

                    b.HasIndex("FormularioEtapaId");

                    b.ToTable("Adm_FlujosFormulariosEtapasAcciones");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioNota", b =>
                {
                    b.Property<int>("FormularioNotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormularioNotaId"));

                    b.Property<int>("FormularioId")
                        .HasColumnType("int");

                    b.Property<string>("TXDescripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TX_Descripcion");

                    b.Property<string>("TXMensaje")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TX_Mensaje");

                    b.Property<string>("TXNombreNota")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TX_NombreNota");

                    b.Property<string>("TXSubject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TX_Subject");

                    b.Property<int?>("TipoUsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("ID_TipoUsuario");

                    b.HasKey("FormularioNotaId");

                    b.ToTable("Adm_FlujoFormularioNotas");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoPantallaUser", b =>
                {
                    b.Property<int>("FlujoUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlujoUserID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormularioEtapaId")
                        .HasColumnType("int");

                    b.Property<string>("GroupType")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("FlujoUserID");

                    b.HasIndex("FormularioEtapaId");

                    b.ToTable("Adm_FlujoPantallaUser");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFormularioEtapaAccioneCampo", b =>
                {
                    b.Property<int>("FormularioEtapaAccionCampoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormularioEtapaAccionCampoId"));

                    b.Property<string>("CampoDB")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("CampoDBIDField")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)")
                        .HasColumnName("CampoDB_IDField");

                    b.Property<string>("CampoDBLongitud")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("CampoDBTipo")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("FormularioEtapaAccionId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenAccion")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TablaBase")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("TipoProcesoCampo")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("FormularioEtapaAccionCampoId");

                    b.HasIndex("FormularioEtapaAccionId");

                    b.ToTable("Adm_FormularioEtapasAccionesCampos");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Forms.FormFlujoPantalla", b =>
                {
                    b.Property<int>("FlujoPantallaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_FORM_FlujoPantalla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlujoPantallaId"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<DateTime>("FechaFlujo")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Flujo");

                    b.Property<string>("FlujoStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Flujo_Status");

                    b.Property<int>("FormaId")
                        .HasColumnType("int")
                        .HasColumnName("ID_Forma");

                    b.Property<int>("FormularioId")
                        .HasColumnType("int")
                        .HasColumnName("ID_Formulario");

                    b.Property<string>("Local")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Notas")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumeroCaso")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Numero_Caso");

                    b.Property<int>("OrdenFlujo")
                        .HasColumnType("int");

                    b.Property<string>("Persona")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("Procesado")
                        .HasColumnType("bit");

                    b.Property<string>("RMO")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Region")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int?>("UsuarioAsignaId")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario_Asigna");

                    b.Property<int?>("UsuarioAsignadoId")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario_Asignado");

                    b.Property<string>("UsuarioFlujoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ID_Usuario_Flujo");

                    b.HasKey("FlujoPantallaId");

                    b.HasIndex("FormularioId");

                    b.ToTable("Form_FlujosPantallas");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Forms.FormFormularioFirma", b =>
                {
                    b.Property<int>("FormularioFirmasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormularioFirmasId"));

                    b.Property<int?>("AdmFlujoFormularioFormularioId")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaFirma")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormularioEtapaId")
                        .HasColumnType("int");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("NumCaso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Num_Caso");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("Revertida")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RevertidaFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rmo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RMO");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ID_Usuario");

                    b.Property<string>("UsuarioRevertidaId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ID_Usuario_Revierte");

                    b.HasKey("FormularioFirmasId");

                    b.HasIndex("AdmFlujoFormularioFormularioId");

                    b.HasIndex("FormularioEtapaId");

                    b.ToTable("Form_FormulariosFirmas");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", b =>
                {
                    b.Property<int>("MenuElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuElementId"));

                    b.Property<string>("Accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Controlador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuElementParentId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("MenuElementId");

                    b.HasIndex("MenuElementParentId");

                    b.ToTable("Adm_MenuElements");

                    b.HasData(
                        new
                        {
                            MenuElementId = 1,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Home",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1297),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-home",
                            Nombre = "Home",
                            Orden = 1
                        },
                        new
                        {
                            MenuElementId = 2,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "SystemConfiguration",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1300),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "System Configuration",
                            Orden = 2
                        },
                        new
                        {
                            MenuElementId = 3,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Parametros",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1302),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 2,
                            Nombre = "Parametros",
                            Orden = 1
                        },
                        new
                        {
                            MenuElementId = 4,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Categorias",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1304),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 2,
                            Nombre = "Categorias",
                            Orden = 2
                        },
                        new
                        {
                            MenuElementId = 5,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Ajustes",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1306),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "Ajustes",
                            Orden = 3
                        },
                        new
                        {
                            MenuElementId = 6,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Roles",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1308),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Roles",
                            Orden = 4
                        },
                        new
                        {
                            MenuElementId = 7,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Usuarios",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1330),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Usuarios",
                            Orden = 5
                        },
                        new
                        {
                            MenuElementId = 8,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Otro",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1332),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Otro",
                            Orden = 6
                        },
                        new
                        {
                            MenuElementId = 9,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "AgregarRol",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1334),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Agregar",
                            Orden = 7
                        },
                        new
                        {
                            MenuElementId = 10,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EditarRol",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1335),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Editar",
                            Orden = 8
                        },
                        new
                        {
                            MenuElementId = 11,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarRol",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1337),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Eliminar",
                            Orden = 9
                        },
                        new
                        {
                            MenuElementId = 12,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "AgregarUsuario",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1339),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Agregar",
                            Orden = 10
                        },
                        new
                        {
                            MenuElementId = 13,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EditarUsuario",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1341),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Editar",
                            Orden = 11
                        },
                        new
                        {
                            MenuElementId = 14,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1345),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Eliminar",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 15,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1347),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 14,
                            Nombre = "Borrado físico",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 16,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1350),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 14,
                            Nombre = "Borrado lógico",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 17,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1352),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "Borrado lógico",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 18,
                            Accion = "Index",
                            Activo = false,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1353),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "Elmento eliminado",
                            Orden = 12
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuRole", b =>
                {
                    b.Property<int>("MenuRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuRoleId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuElementId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuRoleId");

                    b.HasIndex("MenuElementId");

                    b.ToTable("Adm_MenuRole");

                    b.HasData(
                        new
                        {
                            MenuRoleId = 1,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1415),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 1,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 2,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1417),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 2,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 3,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1418),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 3,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 4,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1419),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 4,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 5,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1421),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 5,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 6,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1422),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 6,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 7,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1423),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 7,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 8,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1424),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 8,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 9,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1426),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 9,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 10,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1427),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 10,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 11,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1428),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 11,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 12,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1429),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 12,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 13,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1431),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 13,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 14,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1432),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 14,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 15,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1433),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 15,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 16,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1434),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 16,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 17,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1435),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 17,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 18,
                            Activo = false,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1437),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 18,
                            RoleId = "SU"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro1_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro2_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro3_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro4_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro5_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro6_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro7_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro8_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro9_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Adm_ParametroCategoria");

                    b.HasData(
                        new
                        {
                            CategoriaID = 1,
                            Activo = true,
                            Categoria = "Clasificacion Empleados",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1043),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Clasificaciones"
                        },
                        new
                        {
                            CategoriaID = 2,
                            Activo = true,
                            Categoria = "Curso Aprobado",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1046),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 3,
                            Activo = false,
                            Categoria = "Curso Aprobado Demo",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1048),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 4,
                            Activo = true,
                            Categoria = "Tipo Impedimento",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1050),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 5,
                            Activo = true,
                            Categoria = "Tipo Nombramiento",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1052),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 6,
                            Activo = true,
                            Categoria = "Pueblos",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1055),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Def Pueblos con Dos Niveles de Filtros",
                            TX_Filtro1_Nombre = "Estado",
                            TX_Filtro2_Nombre = "Pais"
                        },
                        new
                        {
                            CategoriaID = 7,
                            Activo = true,
                            Categoria = "Categoria Licencias",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1056),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 8,
                            Activo = true,
                            Categoria = "Firmas",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1058),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "",
                            TX_Filtro1_Nombre = "Posición / Puesto"
                        },
                        new
                        {
                            CategoriaID = 9,
                            Activo = true,
                            Categoria = "Acciones",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1059),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 10,
                            Activo = true,
                            Categoria = "Genero",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1061),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 11,
                            Activo = true,
                            Categoria = "Region",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1062),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 12,
                            Activo = true,
                            Categoria = "Tipo Convocatoria",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1064),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 13,
                            Activo = true,
                            Categoria = "Dependencias",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1065),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 14,
                            Activo = false,
                            Categoria = "Dependencias2",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1066),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 15,
                            Activo = false,
                            Categoria = "Dependencias3",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1068),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 16,
                            Activo = true,
                            Categoria = "Entidades Municipio",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1070),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Def Municipios Tres Niveles Ejemplo",
                            TX_Filtro1_Nombre = "Region",
                            TX_Filtro2_Nombre = "Estado",
                            TX_Filtro3_Nombre = "Pais"
                        },
                        new
                        {
                            CategoriaID = 17,
                            Activo = true,
                            Categoria = "Cantidad Solicitudes",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1071),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 18,
                            Activo = false,
                            Categoria = "Cantidad Solicitudes2",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1073),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 19,
                            Activo = true,
                            Categoria = "Grados Academicos",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1074),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 20,
                            Activo = true,
                            Categoria = "Tipo de Documentos",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1075),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 21,
                            Activo = true,
                            Categoria = "Tipo Reportes",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1077),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 22,
                            Activo = true,
                            Categoria = "RolesReportes",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1079),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 23,
                            Activo = true,
                            Categoria = "RolesMenu",
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1081),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametrosSeleccion", b =>
                {
                    b.Property<int>("ParamterosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParamterosID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParamterosID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Adm_ParametrosSeleccion");

                    b.HasData(
                        new
                        {
                            ParamterosID = 1,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1162),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado"
                        },
                        new
                        {
                            ParamterosID = 2,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1164),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado Temporal"
                        },
                        new
                        {
                            ParamterosID = 3,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1165),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado Contratado"
                        },
                        new
                        {
                            ParamterosID = 4,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1167),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Carrera"
                        },
                        new
                        {
                            ParamterosID = 5,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1168),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Confianza"
                        },
                        new
                        {
                            ParamterosID = 6,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1169),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Base"
                        },
                        new
                        {
                            ParamterosID = 7,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1194),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "San Juan",
                            TX_Filtro1 = "Area Metro",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 8,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1196),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Carolina",
                            TX_Filtro1 = "Area Metro",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 9,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1197),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Arecibo",
                            TX_Filtro1 = "Area Norte",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 10,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1199),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Ponce",
                            TX_Filtro1 = "Area Sur",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 11,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1201),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Orange",
                            TX_Filtro1 = "Central",
                            TX_Filtro2 = "Florida",
                            TX_Filtro3 = "Estados Unidos"
                        },
                        new
                        {
                            ParamterosID = 12,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1202),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "New York City",
                            TX_Filtro1 = "Greater City",
                            TX_Filtro2 = "New York",
                            TX_Filtro3 = "Estados Unidos"
                        },
                        new
                        {
                            ParamterosID = 13,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1219),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Bernardo Acevedo González",
                            Parametro = "BAG",
                            TX_Filtro1 = "Analista de Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 14,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1220),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Carmín Rodríguez Negrón",
                            Parametro = "CRN",
                            TX_Filtro1 = "Directora"
                        },
                        new
                        {
                            ParamterosID = 15,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1225),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Jannette López Falcón",
                            Parametro = "JLF",
                            TX_Filtro1 = "Analista de Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 16,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1226),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Victor Maldonado Martínez",
                            Parametro = "VMM",
                            TX_Filtro1 = "Director"
                        },
                        new
                        {
                            ParamterosID = 17,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1228),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Juan Perez Rodriguez",
                            Parametro = "JPR",
                            TX_Filtro1 = "Analista ASUME"
                        },
                        new
                        {
                            ParamterosID = 18,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1229),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Nancy Calderon Alicea",
                            Parametro = "NCA",
                            TX_Filtro1 = "Especialista Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 19,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1230),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Gabriel Otero Valentin",
                            Parametro = "GOV",
                            TX_Filtro1 = "Analista ADSEF"
                        },
                        new
                        {
                            ParamterosID = 20,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1232),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Leslie Soto Matos",
                            Parametro = "LSM",
                            TX_Filtro1 = "Analista AMSCA"
                        },
                        new
                        {
                            ParamterosID = 21,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1233),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Secretaria Gerencia",
                            Parametro = "SEC-GME",
                            TX_Filtro1 = "Administrador"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmReports", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("ReportDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.ToTable("Adm_ReportAdmin");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1468),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 1,
                            ReportDescription = "Lista los RMS Pendientes Diariamente, selección por Fecha y agrupado por Región",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_GeneradosDiarios",
                            ReportName = "Listado de RMS Generados Diarios (por Región)",
                            ReportParameters = "Fecha",
                            ReportType = "Región"
                        },
                        new
                        {
                            ReportId = 2,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1471),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 3,
                            ReportDescription = "Lista los RMS Completados por los Empleados por rango de fecha y por Región (Todos los Contestados)",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Complete_DateRange",
                            ReportName = "RMS Completados por Empleados rango de Fechas y por Región",
                            ReportParameters = "Fechas",
                            ReportType = "Región"
                        },
                        new
                        {
                            ReportId = 3,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1473),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 2,
                            ReportDescription = "Lista los RMS Completados Validos por los Empleados por rango de fecha y por Región (Solo Validos)",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Complete_DateRangeValid",
                            ReportName = "RMS Completados por Fechas, Región y que son Validos",
                            ReportParameters = "Fechas, Region",
                            ReportType = "Región"
                        },
                        new
                        {
                            ReportId = 4,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1475),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 3,
                            ReportDescription = "Reporte de RMS Completados Validos para reclamos, incluye Numero de RMS para uso en las Asistencias de los Empleados para los RMS Contestados.",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Complete_ValidAssistance",
                            ReportName = "Reporte de RMS Validos Completados Listado para Asistencias de Empleados",
                            ReportParameters = "Fecha, Region",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 5,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1476),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 2,
                            ReportDescription = "Resumen de los RMS enviados, completados, invalidos, seguimientos y validos con porcientos de completados",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRms_Statdistics_DateRangeRegion",
                            ReportName = "RMS Resumen Estadisticas Envíos por Rango Fecha y Región",
                            ReportParameters = "Fecha y Region",
                            ReportType = "Administración"
                        },
                        new
                        {
                            ReportId = 6,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1478),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 1,
                            ReportDescription = "Muestra el Formulario RMS según llenado por los Trabajadores Sociales",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CAP_WorkDetailRange",
                            ReportName = "Formulario RMS llenados por Fecha ",
                            ReportParameters = "Fecha",
                            ReportType = "Administración"
                        },
                        new
                        {
                            ReportId = 7,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1480),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 4,
                            ReportDescription = "El reporte de Cost Allocation Plan resumen de los RMS entrados por Grant Diarios",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CostAllocationDaily",
                            ReportName = "Cost Allocation Plan Reporte Diario",
                            ReportParameters = "Fecha",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 8,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1481),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 5,
                            ReportDescription = "El reporte de Cost Allocation Plan resumen de los RMS entrados por Grant para el Mes seleccionado.",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CostAllocationMonthly",
                            ReportName = "Cost Allocation Plan Reporte Mensual",
                            ReportParameters = "Fecha",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 9,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1483),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 7,
                            ReportDescription = "El reporte de Cost Allocation Plan resumen de los RMS entrados por Grant Trimestrales",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CostAllocationQuarter",
                            ReportName = "Cost Allocation Plan Reporte Trimestral",
                            ReportParameters = "Fecha",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 10,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1485),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 3,
                            ReportDescription = "Este Reporte muestra todas las Observaciones entradas por los usuarios en un rango de fechas con sus respectivos Títulos y Grants por rango de Fecha y selección de Validos o Invalidos para el CAP",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Submitted_DateRange",
                            ReportName = "Observaciones Completadas por Rango de Fecha (Selección Validas)",
                            ReportParameters = "Fechas",
                            ReportType = "Administración"
                        },
                        new
                        {
                            ReportId = 11,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1486),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 1,
                            ReportDescription = "RMS Matrix Distribution Report for the CAP Titile Distribution",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CAP_Matrix",
                            ReportName = "RMS Matrix",
                            ReportParameters = "Fechas",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 12,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(1489),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 2,
                            ReportDescription = "Listado de RMS Validos para completar el Schedule D del CAP",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CAP_ScheduleD",
                            ReportName = "Schedule D Listado RMS",
                            ReportParameters = "Fechas",
                            ReportType = "Finanzas"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmReportsRole", b =>
                {
                    b.Property<int>("ReportRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportRoleId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportRoleId");

                    b.HasIndex("ReportId");

                    b.ToTable("Adm_ReportAdminRole");

                    b.HasData(
                        new
                        {
                            ReportRoleId = 1,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2046),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 1,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 2,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2047),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 2,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 3,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2049),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 3,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 4,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2050),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 4,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 5,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2052),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 5,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 6,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2053),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 6,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 7,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2054),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 7,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 8,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2055),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 8,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 9,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2056),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 9,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 10,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2058),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 10,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 11,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2060),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 11,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 12,
                            Activo = true,
                            CreateDate = new DateTime(2024, 8, 19, 20, 58, 14, 273, DateTimeKind.Local).AddTicks(2061),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 12,
                            RoleId = "SU"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioEtapa", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.Flujos.AdmFlujoFormulario", "AdmFlujoFormulario")
                        .WithMany("AdmFlujoFormularioEtapas")
                        .HasForeignKey("FormularioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioNota", "AdmFlujoFormularioNotaEnd")
                        .WithMany("AdmFlujoFormularioEtapasEnd")
                        .HasForeignKey("NotaEndId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AdmFlujoFormularioNotaEnd");

                    b.HasOne("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioNota", "AdmFlujoFormularioNotaStart")
                        .WithMany("AdmFlujoFormularioEtapasStart")
                        .HasForeignKey("NotaStartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AdmFlujoFormularioNotaStart");

                    b.Navigation("AdmFlujoFormulario");

                    b.Navigation("AdmFlujoFormularioNotaEnd");

                    b.Navigation("AdmFlujoFormularioNotaStart");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioEtapaAccion", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioEtapa", "AdmFlujoFormularioEtapa")
                        .WithMany("AdmFlujoFormularioEtapaAcciones")
                        .HasForeignKey("FormularioEtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmFlujoFormularioEtapa");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoPantallaUser", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioEtapa", "AdmFlujoFormularioEtapa")
                        .WithMany()
                        .HasForeignKey("FormularioEtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmFlujoFormularioEtapa");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFormularioEtapaAccioneCampo", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioEtapaAccion", "AdmFlujoFormularioEtapaAccion")
                        .WithMany("AdmFormularioEtapaAccioneCampos")
                        .HasForeignKey("FormularioEtapaAccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmFlujoFormularioEtapaAccion");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Forms.FormFlujoPantalla", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.Flujos.AdmFlujoFormulario", "AdmFlujoFormulario")
                        .WithMany("FormFlujoPantallas")
                        .HasForeignKey("FormularioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmFlujoFormulario");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Forms.FormFormularioFirma", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.Flujos.AdmFlujoFormulario", null)
                        .WithMany("FormFormularioFirmas")
                        .HasForeignKey("AdmFlujoFormularioFormularioId");

                    b.HasOne("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioEtapa", "AdmFlujoFormularioEtapa")
                        .WithMany("FormFormularioFirmas")
                        .HasForeignKey("FormularioEtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmFlujoFormularioEtapa");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", null)
                        .WithMany("AdmMenuChildElements")
                        .HasForeignKey("MenuElementParentId");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuRole", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", "AdmMenuElement")
                        .WithMany("AdmMenuRoles")
                        .HasForeignKey("MenuElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmMenuElement");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametrosSeleccion", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", "AdmParametroCategoria")
                        .WithMany("AdmParametrosSeleccions")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmParametroCategoria");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmReportsRole", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmReports", "AdmReports")
                        .WithMany("AdmReportsRoles")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmReports");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoFormulario", b =>
                {
                    b.Navigation("AdmFlujoFormularioEtapas");

                    b.Navigation("FormFlujoPantallas");

                    b.Navigation("FormFormularioFirmas");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioEtapa", b =>
                {
                    b.Navigation("AdmFlujoFormularioEtapaAcciones");

                    b.Navigation("FormFormularioFirmas");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioEtapaAccion", b =>
                {
                    b.Navigation("AdmFormularioEtapaAccioneCampos");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.Flujos.AdmFlujoFormularioNota", b =>
                {
                    b.Navigation("AdmFlujoFormularioEtapasEnd");

                    b.Navigation("AdmFlujoFormularioEtapasStart");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", b =>
                {
                    b.Navigation("AdmMenuChildElements");

                    b.Navigation("AdmMenuRoles");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", b =>
                {
                    b.Navigation("AdmParametrosSeleccions");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmReports", b =>
                {
                    b.Navigation("AdmReportsRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
