// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRAMS.Infraestructure.Data.SystemConfiguration;

#nullable disable

namespace PRAMS.Configuration.Migrations
{
    [DbContext(typeof(AppConfigDbContext))]
    partial class AppConfigDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", b =>
                {
                    b.Property<int>("MenuElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuElementId"));

                    b.Property<string>("Accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Controlador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuElementParentId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("MenuElementId");

                    b.HasIndex("MenuElementParentId");

                    b.ToTable("Adm_MenuElements");

                    b.HasData(
                        new
                        {
                            MenuElementId = 1,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Home",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4616),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-home",
                            Nombre = "Home",
                            Orden = 1
                        },
                        new
                        {
                            MenuElementId = 2,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "SystemConfiguration",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4618),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "System Configuration",
                            Orden = 2
                        },
                        new
                        {
                            MenuElementId = 3,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Parametros",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4621),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 2,
                            Nombre = "Parametros",
                            Orden = 1
                        },
                        new
                        {
                            MenuElementId = 4,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Categorias",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4623),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 2,
                            Nombre = "Categorias",
                            Orden = 2
                        },
                        new
                        {
                            MenuElementId = 5,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Ajustes",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4625),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "Ajustes",
                            Orden = 3
                        },
                        new
                        {
                            MenuElementId = 6,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Roles",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4626),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Roles",
                            Orden = 4
                        },
                        new
                        {
                            MenuElementId = 7,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Usuarios",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4628),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Usuarios",
                            Orden = 5
                        },
                        new
                        {
                            MenuElementId = 8,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Otro",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4630),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Otro",
                            Orden = 6
                        },
                        new
                        {
                            MenuElementId = 9,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "AgregarRol",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4632),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Agregar",
                            Orden = 7
                        },
                        new
                        {
                            MenuElementId = 10,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EditarRol",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4634),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Editar",
                            Orden = 8
                        },
                        new
                        {
                            MenuElementId = 11,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarRol",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4636),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Eliminar",
                            Orden = 9
                        },
                        new
                        {
                            MenuElementId = 12,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "AgregarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4638),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Agregar",
                            Orden = 10
                        },
                        new
                        {
                            MenuElementId = 13,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EditarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4640),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Editar",
                            Orden = 11
                        },
                        new
                        {
                            MenuElementId = 14,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4642),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Eliminar",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 15,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4644),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 14,
                            Nombre = "Borrado físico",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 16,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4646),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 14,
                            Nombre = "Borrado lógico",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 17,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4647),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "Borrado lógico",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 18,
                            Accion = "Index",
                            Activo = false,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4649),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "Elmento eliminado",
                            Orden = 12
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuRole", b =>
                {
                    b.Property<int>("MenuRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuRoleId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuElementId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuRoleId");

                    b.HasIndex("MenuElementId");

                    b.ToTable("Adm_MenuRole");

                    b.HasData(
                        new
                        {
                            MenuRoleId = 1,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4702),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 1,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 2,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4704),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 2,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 3,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4705),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 3,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 4,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4706),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 4,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 5,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4708),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 5,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 6,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4709),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 6,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 7,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4710),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 7,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 8,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4711),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 8,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 9,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4712),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 9,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 10,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4714),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 10,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 11,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4715),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 11,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 12,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4716),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 12,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 13,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4717),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 13,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 14,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4718),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 14,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 15,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4719),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 15,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 16,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4720),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 16,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 17,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4722),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 17,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 18,
                            Activo = false,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4723),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 18,
                            RoleId = "SU"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro1_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro2_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro3_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro4_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro5_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro6_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro7_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro8_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro9_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Adm_ParametroCategoria");

                    b.HasData(
                        new
                        {
                            CategoriaID = 1,
                            Activo = true,
                            Categoria = "Clasificacion Empleados",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4368),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Clasificaciones"
                        },
                        new
                        {
                            CategoriaID = 2,
                            Activo = true,
                            Categoria = "Curso Aprobado",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4371),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 3,
                            Activo = false,
                            Categoria = "Curso Aprobado Demo",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4373),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 4,
                            Activo = true,
                            Categoria = "Tipo Impedimento",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4374),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 5,
                            Activo = true,
                            Categoria = "Tipo Nombramiento",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4376),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 6,
                            Activo = true,
                            Categoria = "Pueblos",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4378),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Def Pueblos con Dos Niveles de Filtros",
                            TX_Filtro1_Nombre = "Estado",
                            TX_Filtro2_Nombre = "Pais"
                        },
                        new
                        {
                            CategoriaID = 7,
                            Activo = true,
                            Categoria = "Categoria Licencias",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4379),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 8,
                            Activo = true,
                            Categoria = "Firmas",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4381),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "",
                            TX_Filtro1_Nombre = "Posición / Puesto"
                        },
                        new
                        {
                            CategoriaID = 9,
                            Activo = true,
                            Categoria = "Acciones",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4382),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 10,
                            Activo = true,
                            Categoria = "Genero",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4384),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 11,
                            Activo = true,
                            Categoria = "Region",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4385),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 12,
                            Activo = true,
                            Categoria = "Tipo Convocatoria",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4387),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 13,
                            Activo = true,
                            Categoria = "Dependencias",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4388),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 14,
                            Activo = false,
                            Categoria = "Dependencias2",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4390),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 15,
                            Activo = false,
                            Categoria = "Dependencias3",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4391),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 16,
                            Activo = true,
                            Categoria = "Entidades Municipio",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4393),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Def Municipios Tres Niveles Ejemplo",
                            TX_Filtro1_Nombre = "Region",
                            TX_Filtro2_Nombre = "Estado",
                            TX_Filtro3_Nombre = "Pais"
                        },
                        new
                        {
                            CategoriaID = 17,
                            Activo = true,
                            Categoria = "Cantidad Solicitudes",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4394),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 18,
                            Activo = false,
                            Categoria = "Cantidad Solicitudes2",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4396),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 19,
                            Activo = true,
                            Categoria = "Grados Academicos",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4397),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 20,
                            Activo = true,
                            Categoria = "Tipo de Documentos",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4399),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 21,
                            Activo = true,
                            Categoria = "Tipo Reportes",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4400),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 22,
                            Activo = true,
                            Categoria = "RolesReportes",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4401),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 23,
                            Activo = true,
                            Categoria = "RolesMenu",
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4403),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametrosSeleccion", b =>
                {
                    b.Property<int>("ParamterosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParamterosID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParamterosID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Adm_ParametrosSeleccion");

                    b.HasData(
                        new
                        {
                            ParamterosID = 1,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4489),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado"
                        },
                        new
                        {
                            ParamterosID = 2,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4491),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado Temporal"
                        },
                        new
                        {
                            ParamterosID = 3,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4493),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado Contratado"
                        },
                        new
                        {
                            ParamterosID = 4,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4494),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Carrera"
                        },
                        new
                        {
                            ParamterosID = 5,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4495),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Confianza"
                        },
                        new
                        {
                            ParamterosID = 6,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4496),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Base"
                        },
                        new
                        {
                            ParamterosID = 7,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4517),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "San Juan",
                            TX_Filtro1 = "Area Metro",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 8,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4519),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Carolina",
                            TX_Filtro1 = "Area Metro",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 9,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4521),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Arecibo",
                            TX_Filtro1 = "Area Norte",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 10,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4541),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Ponce",
                            TX_Filtro1 = "Area Sur",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 11,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4543),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Orange",
                            TX_Filtro1 = "Central",
                            TX_Filtro2 = "Florida",
                            TX_Filtro3 = "Estados Unidos"
                        },
                        new
                        {
                            ParamterosID = 12,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4544),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "New York City",
                            TX_Filtro1 = "Greater City",
                            TX_Filtro2 = "New York",
                            TX_Filtro3 = "Estados Unidos"
                        },
                        new
                        {
                            ParamterosID = 13,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4558),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Bernardo Acevedo González",
                            Parametro = "BAG",
                            TX_Filtro1 = "Analista de Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 14,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4560),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Carmín Rodríguez Negrón",
                            Parametro = "CRN",
                            TX_Filtro1 = "Directora"
                        },
                        new
                        {
                            ParamterosID = 15,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4561),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Jannette López Falcón",
                            Parametro = "JLF",
                            TX_Filtro1 = "Analista de Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 16,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4562),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Victor Maldonado Martínez",
                            Parametro = "VMM",
                            TX_Filtro1 = "Director"
                        },
                        new
                        {
                            ParamterosID = 17,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4564),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Juan Perez Rodriguez",
                            Parametro = "JPR",
                            TX_Filtro1 = "Analista ASUME"
                        },
                        new
                        {
                            ParamterosID = 18,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4565),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Nancy Calderon Alicea",
                            Parametro = "NCA",
                            TX_Filtro1 = "Especialista Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 19,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4567),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Gabriel Otero Valentin",
                            Parametro = "GOV",
                            TX_Filtro1 = "Analista ADSEF"
                        },
                        new
                        {
                            ParamterosID = 20,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4568),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Leslie Soto Matos",
                            Parametro = "LSM",
                            TX_Filtro1 = "Analista AMSCA"
                        },
                        new
                        {
                            ParamterosID = 21,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4569),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Secretaria Gerencia",
                            Parametro = "SEC-GME",
                            TX_Filtro1 = "Administrador"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmReports", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("ReportDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.ToTable("Adm_ReportAdmin");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4750),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 1,
                            ReportDescription = "Lista los RMS Pendientes Diariamente, selección por Fecha y agrupado por Región",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_GeneradosDiarios",
                            ReportName = "Listado de RMS Generados Diarios (por Región)",
                            ReportParameters = "Fecha",
                            ReportType = "Región"
                        },
                        new
                        {
                            ReportId = 2,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4753),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 3,
                            ReportDescription = "Lista los RMS Completados por los Empleados por rango de fecha y por Región (Todos los Contestados)",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Complete_DateRange",
                            ReportName = "RMS Completados por Empleados rango de Fechas y por Región",
                            ReportParameters = "Fechas",
                            ReportType = "Región"
                        },
                        new
                        {
                            ReportId = 3,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4754),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 2,
                            ReportDescription = "Lista los RMS Completados Validos por los Empleados por rango de fecha y por Región (Solo Validos)",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Complete_DateRangeValid",
                            ReportName = "RMS Completados por Fechas, Región y que son Validos",
                            ReportParameters = "Fechas, Region",
                            ReportType = "Región"
                        },
                        new
                        {
                            ReportId = 4,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4756),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 3,
                            ReportDescription = "Reporte de RMS Completados Validos para reclamos, incluye Numero de RMS para uso en las Asistencias de los Empleados para los RMS Contestados.",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Complete_ValidAssistance",
                            ReportName = "Reporte de RMS Validos Completados Listado para Asistencias de Empleados",
                            ReportParameters = "Fecha, Region",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 5,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4758),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 2,
                            ReportDescription = "Resumen de los RMS enviados, completados, invalidos, seguimientos y validos con porcientos de completados",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRms_Statdistics_DateRangeRegion",
                            ReportName = "RMS Resumen Estadisticas Envíos por Rango Fecha y Región",
                            ReportParameters = "Fecha y Region",
                            ReportType = "Administración"
                        },
                        new
                        {
                            ReportId = 6,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4760),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 1,
                            ReportDescription = "Muestra el Formulario RMS según llenado por los Trabajadores Sociales",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CAP_WorkDetailRange",
                            ReportName = "Formulario RMS llenados por Fecha ",
                            ReportParameters = "Fecha",
                            ReportType = "Administración"
                        },
                        new
                        {
                            ReportId = 7,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4762),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 4,
                            ReportDescription = "El reporte de Cost Allocation Plan resumen de los RMS entrados por Grant Diarios",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CostAllocationDaily",
                            ReportName = "Cost Allocation Plan Reporte Diario",
                            ReportParameters = "Fecha",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 8,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4764),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 5,
                            ReportDescription = "El reporte de Cost Allocation Plan resumen de los RMS entrados por Grant para el Mes seleccionado.",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CostAllocationMonthly",
                            ReportName = "Cost Allocation Plan Reporte Mensual",
                            ReportParameters = "Fecha",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 9,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4765),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 7,
                            ReportDescription = "El reporte de Cost Allocation Plan resumen de los RMS entrados por Grant Trimestrales",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CostAllocationQuarter",
                            ReportName = "Cost Allocation Plan Reporte Trimestral",
                            ReportParameters = "Fecha",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 10,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4767),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 3,
                            ReportDescription = "Este Reporte muestra todas las Observaciones entradas por los usuarios en un rango de fechas con sus respectivos Títulos y Grants por rango de Fecha y selección de Validos o Invalidos para el CAP",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Submitted_DateRange",
                            ReportName = "Observaciones Completadas por Rango de Fecha (Selección Validas)",
                            ReportParameters = "Fechas",
                            ReportType = "Administración"
                        },
                        new
                        {
                            ReportId = 11,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4769),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 1,
                            ReportDescription = "RMS Matrix Distribution Report for the CAP Titile Distribution",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CAP_Matrix",
                            ReportName = "RMS Matrix",
                            ReportParameters = "Fechas",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 12,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4770),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 2,
                            ReportDescription = "Listado de RMS Validos para completar el Schedule D del CAP",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CAP_ScheduleD",
                            ReportName = "Schedule D Listado RMS",
                            ReportParameters = "Fechas",
                            ReportType = "Finanzas"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmReportsRole", b =>
                {
                    b.Property<int>("ReportRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportRoleId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportRoleId");

                    b.HasIndex("ReportId");

                    b.ToTable("Adm_ReportAdminRole");

                    b.HasData(
                        new
                        {
                            ReportRoleId = 1,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4794),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 1,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 2,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4796),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 2,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 3,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4797),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 3,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 4,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4798),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 4,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 5,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4799),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 5,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 6,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4801),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 6,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 7,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4802),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 7,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 8,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4803),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 8,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 9,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4805),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 9,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 10,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4806),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 10,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 11,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4807),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 11,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 12,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 21, 4, 32, 673, DateTimeKind.Local).AddTicks(4808),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 12,
                            RoleId = "SU"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", null)
                        .WithMany("AdmMenuChildElements")
                        .HasForeignKey("MenuElementParentId");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuRole", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", "AdmMenuElement")
                        .WithMany("AdmMenuRoles")
                        .HasForeignKey("MenuElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmMenuElement");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametrosSeleccion", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", "AdmParametroCategoria")
                        .WithMany("AdmParametrosSeleccions")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmParametroCategoria");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmReportsRole", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmReports", "AdmReports")
                        .WithMany("AdmReportsRoles")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmReports");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", b =>
                {
                    b.Navigation("AdmMenuChildElements");

                    b.Navigation("AdmMenuRoles");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", b =>
                {
                    b.Navigation("AdmParametrosSeleccions");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmReports", b =>
                {
                    b.Navigation("AdmReportsRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
