// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRAMS.Infraestructure.Data.SystemConfiguration;

#nullable disable

namespace PRAMS.Configuration.Migrations
{
    [DbContext(typeof(AppConfigDbContext))]
    partial class AppConfigDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdmReportsAdmReportsRole", b =>
                {
                    b.Property<int>("AdmReportsReportId")
                        .HasColumnType("int");

                    b.Property<int>("AdmReportsRolesReportRoleId")
                        .HasColumnType("int");

                    b.HasKey("AdmReportsReportId", "AdmReportsRolesReportRoleId");

                    b.HasIndex("AdmReportsRolesReportRoleId");

                    b.ToTable("AdmReportsAdmReportsRole");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", b =>
                {
                    b.Property<int>("MenuElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuElementId"));

                    b.Property<string>("Accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Controlador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuElementParentId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("MenuElementId");

                    b.HasIndex("MenuElementParentId");

                    b.ToTable("Adm_MenuElements");

                    b.HasData(
                        new
                        {
                            MenuElementId = 1,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Home",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1142),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-home",
                            Nombre = "Home",
                            Orden = 1
                        },
                        new
                        {
                            MenuElementId = 2,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "SystemConfiguration",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1145),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "System Configuration",
                            Orden = 2
                        },
                        new
                        {
                            MenuElementId = 3,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Parametros",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1148),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 2,
                            Nombre = "Parametros",
                            Orden = 1
                        },
                        new
                        {
                            MenuElementId = 4,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Categorias",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1150),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 2,
                            Nombre = "Categorias",
                            Orden = 2
                        },
                        new
                        {
                            MenuElementId = 5,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Ajustes",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1152),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "Ajustes",
                            Orden = 3
                        },
                        new
                        {
                            MenuElementId = 6,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Roles",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1155),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Roles",
                            Orden = 4
                        },
                        new
                        {
                            MenuElementId = 7,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Usuarios",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1158),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Usuarios",
                            Orden = 5
                        },
                        new
                        {
                            MenuElementId = 8,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "Otro",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1160),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 5,
                            Nombre = "Otro",
                            Orden = 6
                        },
                        new
                        {
                            MenuElementId = 9,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "AgregarRol",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1162),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Agregar",
                            Orden = 7
                        },
                        new
                        {
                            MenuElementId = 10,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EditarRol",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1164),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Editar",
                            Orden = 8
                        },
                        new
                        {
                            MenuElementId = 11,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarRol",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1166),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 6,
                            Nombre = "Eliminar",
                            Orden = 9
                        },
                        new
                        {
                            MenuElementId = 12,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "AgregarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1168),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Agregar",
                            Orden = 10
                        },
                        new
                        {
                            MenuElementId = 13,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EditarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1170),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Editar",
                            Orden = 11
                        },
                        new
                        {
                            MenuElementId = 14,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1173),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 7,
                            Nombre = "Eliminar",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 15,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1175),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 14,
                            Nombre = "Borrado físico",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 16,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1177),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            MenuElementParentId = 14,
                            Nombre = "Borrado lógico",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 17,
                            Accion = "Index",
                            Activo = true,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1179),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "Borrado lógico",
                            Orden = 12
                        },
                        new
                        {
                            MenuElementId = 18,
                            Accion = "Index",
                            Activo = false,
                            Controlador = "EliminarUsuario",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1181),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Icono = "fas fa-cogs",
                            Nombre = "Elmento eliminado",
                            Orden = 12
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuRole", b =>
                {
                    b.Property<int>("MenuRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuRoleId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuElementId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuRoleId");

                    b.HasIndex("MenuElementId");

                    b.ToTable("Adm_MenuRole");

                    b.HasData(
                        new
                        {
                            MenuRoleId = 1,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1212),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 1,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 2,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1214),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 2,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 3,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1216),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 3,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 4,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1217),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 4,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 5,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1219),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 5,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 6,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1220),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 6,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 7,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1222),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 7,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 8,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1223),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 8,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 9,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1224),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 9,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 10,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1226),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 10,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 11,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1227),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 11,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 12,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1229),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 12,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 13,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1230),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 13,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 14,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1232),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 14,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 15,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1233),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 15,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 16,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1234),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 16,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 17,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1236),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 17,
                            RoleId = "SU"
                        },
                        new
                        {
                            MenuRoleId = 18,
                            Activo = false,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1237),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            MenuElementId = 18,
                            RoleId = "SU"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro1_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro2_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro3_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro4_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro5_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro6_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro7_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro8_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro9_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Adm_ParametroCategoria");

                    b.HasData(
                        new
                        {
                            CategoriaID = 1,
                            Activo = true,
                            Categoria = "Clasificacion Empleados",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(848),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Clasificaciones"
                        },
                        new
                        {
                            CategoriaID = 2,
                            Activo = true,
                            Categoria = "Curso Aprobado",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(851),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 3,
                            Activo = false,
                            Categoria = "Curso Aprobado Demo",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(853),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 4,
                            Activo = true,
                            Categoria = "Tipo Impedimento",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(854),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 5,
                            Activo = true,
                            Categoria = "Tipo Nombramiento",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(856),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 6,
                            Activo = true,
                            Categoria = "Pueblos",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(858),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Def Pueblos con Dos Niveles de Filtros",
                            TX_Filtro1_Nombre = "Estado",
                            TX_Filtro2_Nombre = "Pais"
                        },
                        new
                        {
                            CategoriaID = 7,
                            Activo = true,
                            Categoria = "Categoria Licencias",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(860),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 8,
                            Activo = true,
                            Categoria = "Firmas",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(862),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "",
                            TX_Filtro1_Nombre = "Posición / Puesto"
                        },
                        new
                        {
                            CategoriaID = 9,
                            Activo = true,
                            Categoria = "Acciones",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(887),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 10,
                            Activo = true,
                            Categoria = "Genero",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(889),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 11,
                            Activo = true,
                            Categoria = "Region",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(891),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 12,
                            Activo = true,
                            Categoria = "Tipo Convocatoria",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(892),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 13,
                            Activo = true,
                            Categoria = "Dependencias",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(894),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 14,
                            Activo = false,
                            Categoria = "Dependencias2",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(896),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 15,
                            Activo = false,
                            Categoria = "Dependencias3",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(897),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 16,
                            Activo = true,
                            Categoria = "Entidades Municipio",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(900),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Def Municipios Tres Niveles Ejemplo",
                            TX_Filtro1_Nombre = "Region",
                            TX_Filtro2_Nombre = "Estado",
                            TX_Filtro3_Nombre = "Pais"
                        },
                        new
                        {
                            CategoriaID = 17,
                            Activo = true,
                            Categoria = "Cantidad Solicitudes",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(901),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 18,
                            Activo = false,
                            Categoria = "Cantidad Solicitudes2",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(903),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 19,
                            Activo = true,
                            Categoria = "Grados Academicos",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(904),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 20,
                            Activo = true,
                            Categoria = "Tipo de Documentos",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(906),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 21,
                            Activo = true,
                            Categoria = "Tipo Reportes",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(908),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 22,
                            Activo = true,
                            Categoria = "RolesReportes",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(909),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        },
                        new
                        {
                            CategoriaID = 23,
                            Activo = true,
                            Categoria = "RolesMenu",
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(911),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = ""
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametrosSeleccion", b =>
                {
                    b.Property<int>("ParamterosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParamterosID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_Filtro9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParamterosID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Adm_ParametrosSeleccion");

                    b.HasData(
                        new
                        {
                            ParamterosID = 1,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(995),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado"
                        },
                        new
                        {
                            ParamterosID = 2,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(998),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado Temporal"
                        },
                        new
                        {
                            ParamterosID = 3,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1000),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado Contratado"
                        },
                        new
                        {
                            ParamterosID = 4,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1001),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Carrera"
                        },
                        new
                        {
                            ParamterosID = 5,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1003),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Confianza"
                        },
                        new
                        {
                            ParamterosID = 6,
                            Activo = true,
                            CategoriaID = 1,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1005),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Empleado de Base"
                        },
                        new
                        {
                            ParamterosID = 7,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1034),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "San Juan",
                            TX_Filtro1 = "Area Metro",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 8,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1037),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Carolina",
                            TX_Filtro1 = "Area Metro",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 9,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1039),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Arecibo",
                            TX_Filtro1 = "Area Norte",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 10,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1041),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Ponce",
                            TX_Filtro1 = "Area Sur",
                            TX_Filtro2 = "PR",
                            TX_Filtro3 = "Puerto Rico"
                        },
                        new
                        {
                            ParamterosID = 11,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1043),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "Orange",
                            TX_Filtro1 = "Central",
                            TX_Filtro2 = "Florida",
                            TX_Filtro3 = "Estados Unidos"
                        },
                        new
                        {
                            ParamterosID = 12,
                            Activo = true,
                            CategoriaID = 16,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1045),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Parametro = "New York City",
                            TX_Filtro1 = "Greater City",
                            TX_Filtro2 = "New York",
                            TX_Filtro3 = "Estados Unidos"
                        },
                        new
                        {
                            ParamterosID = 13,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1062),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Bernardo Acevedo González",
                            Parametro = "BAG",
                            TX_Filtro1 = "Analista de Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 14,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1064),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Carmín Rodríguez Negrón",
                            Parametro = "CRN",
                            TX_Filtro1 = "Directora"
                        },
                        new
                        {
                            ParamterosID = 15,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1066),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Jannette López Falcón",
                            Parametro = "JLF",
                            TX_Filtro1 = "Analista de Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 16,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1090),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Victor Maldonado Martínez",
                            Parametro = "VMM",
                            TX_Filtro1 = "Director"
                        },
                        new
                        {
                            ParamterosID = 17,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1092),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Juan Perez Rodriguez",
                            Parametro = "JPR",
                            TX_Filtro1 = "Analista ASUME"
                        },
                        new
                        {
                            ParamterosID = 18,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1094),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Nancy Calderon Alicea",
                            Parametro = "NCA",
                            TX_Filtro1 = "Especialista Recursos Humanos"
                        },
                        new
                        {
                            ParamterosID = 19,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1095),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Gabriel Otero Valentin",
                            Parametro = "GOV",
                            TX_Filtro1 = "Analista ADSEF"
                        },
                        new
                        {
                            ParamterosID = 20,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1097),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Leslie Soto Matos",
                            Parametro = "LSM",
                            TX_Filtro1 = "Analista AMSCA"
                        },
                        new
                        {
                            ParamterosID = 21,
                            Activo = true,
                            CategoriaID = 8,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1099),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Descripcion = "Secretaria Gerencia",
                            Parametro = "SEC-GME",
                            TX_Filtro1 = "Administrador"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmReports", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("ReportDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.ToTable("Adm_ReportAdmin");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1322),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 1,
                            ReportDescription = "Lista los RMS Pendientes Diariamente, selección por Fecha y agrupado por Región",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_GeneradosDiarios",
                            ReportName = "Listado de RMS Generados Diarios (por Región)",
                            ReportParameters = "Fecha",
                            ReportType = "Región"
                        },
                        new
                        {
                            ReportId = 2,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1325),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 3,
                            ReportDescription = "Lista los RMS Completados por los Empleados por rango de fecha y por Región (Todos los Contestados)",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Complete_DateRange",
                            ReportName = "RMS Completados por Empleados rango de Fechas y por Región",
                            ReportParameters = "Fechas",
                            ReportType = "Región"
                        },
                        new
                        {
                            ReportId = 3,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1327),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 2,
                            ReportDescription = "Lista los RMS Completados Validos por los Empleados por rango de fecha y por Región (Solo Validos)",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Complete_DateRangeValid",
                            ReportName = "RMS Completados por Fechas, Región y que son Validos",
                            ReportParameters = "Fechas, Region",
                            ReportType = "Región"
                        },
                        new
                        {
                            ReportId = 4,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1329),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 3,
                            ReportDescription = "Reporte de RMS Completados Validos para reclamos, incluye Numero de RMS para uso en las Asistencias de los Empleados para los RMS Contestados.",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Complete_ValidAssistance",
                            ReportName = "Reporte de RMS Validos Completados Listado para Asistencias de Empleados",
                            ReportParameters = "Fecha, Region",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 5,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1331),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 2,
                            ReportDescription = "Resumen de los RMS enviados, completados, invalidos, seguimientos y validos con porcientos de completados",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRms_Statdistics_DateRangeRegion",
                            ReportName = "RMS Resumen Estadisticas Envíos por Rango Fecha y Región",
                            ReportParameters = "Fecha y Region",
                            ReportType = "Administración"
                        },
                        new
                        {
                            ReportId = 6,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1333),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 1,
                            ReportDescription = "Muestra el Formulario RMS según llenado por los Trabajadores Sociales",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CAP_WorkDetailRange",
                            ReportName = "Formulario RMS llenados por Fecha ",
                            ReportParameters = "Fecha",
                            ReportType = "Administración"
                        },
                        new
                        {
                            ReportId = 7,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1335),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 4,
                            ReportDescription = "El reporte de Cost Allocation Plan resumen de los RMS entrados por Grant Diarios",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CostAllocationDaily",
                            ReportName = "Cost Allocation Plan Reporte Diario",
                            ReportParameters = "Fecha",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 8,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1337),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 5,
                            ReportDescription = "El reporte de Cost Allocation Plan resumen de los RMS entrados por Grant para el Mes seleccionado.",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CostAllocationMonthly",
                            ReportName = "Cost Allocation Plan Reporte Mensual",
                            ReportParameters = "Fecha",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 9,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1339),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 7,
                            ReportDescription = "El reporte de Cost Allocation Plan resumen de los RMS entrados por Grant Trimestrales",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CostAllocationQuarter",
                            ReportName = "Cost Allocation Plan Reporte Trimestral",
                            ReportParameters = "Fecha",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 10,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1341),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 3,
                            ReportDescription = "Este Reporte muestra todas las Observaciones entradas por los usuarios en un rango de fechas con sus respectivos Títulos y Grants por rango de Fecha y selección de Validos o Invalidos para el CAP",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_Submitted_DateRange",
                            ReportName = "Observaciones Completadas por Rango de Fecha (Selección Validas)",
                            ReportParameters = "Fechas",
                            ReportType = "Administración"
                        },
                        new
                        {
                            ReportId = 11,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1343),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 1,
                            ReportDescription = "RMS Matrix Distribution Report for the CAP Titile Distribution",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CAP_Matrix",
                            ReportName = "RMS Matrix",
                            ReportParameters = "Fechas",
                            ReportType = "Finanzas"
                        },
                        new
                        {
                            ReportId = 12,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 883, DateTimeKind.Local).AddTicks(1345),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            Orden = 2,
                            ReportDescription = "Listado de RMS Validos para completar el Schedule D del CAP",
                            ReportLink = "Reports/Pages/Report.aspx?ItemPath=%2fRMS+Reports%2fRMS_CAP_ScheduleD",
                            ReportName = "Schedule D Listado RMS",
                            ReportParameters = "Fechas",
                            ReportType = "Finanzas"
                        });
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmReportsRole", b =>
                {
                    b.Property<int>("ReportRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportRoleId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportRoleId");

                    b.HasIndex("ReportId");

                    b.ToTable("Adm_ReportAdminRole");

                    b.HasData(
                        new
                        {
                            ReportRoleId = 1,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2632),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 1,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 2,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2634),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 2,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 3,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2636),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 3,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 4,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2662),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 4,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 5,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2664),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 5,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 6,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2666),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 6,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 7,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2667),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 7,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 8,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2669),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 8,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 9,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2670),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 9,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 10,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2672),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 10,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 11,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2673),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 11,
                            RoleId = "SU"
                        },
                        new
                        {
                            ReportRoleId = 12,
                            Activo = true,
                            CreateDate = new DateTime(2024, 7, 7, 14, 32, 2, 884, DateTimeKind.Local).AddTicks(2675),
                            CreateUser = "03334448-73b4-438f-8fdf-784dbab58150",
                            ReportId = 12,
                            RoleId = "SU"
                        });
                });

            modelBuilder.Entity("AdmReportsAdmReportsRole", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmReports", null)
                        .WithMany()
                        .HasForeignKey("AdmReportsReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmReportsRole", null)
                        .WithMany()
                        .HasForeignKey("AdmReportsRolesReportRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", null)
                        .WithMany("AdmMenuChildElements")
                        .HasForeignKey("MenuElementParentId");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuRole", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", "AdmMenuElement")
                        .WithMany("AdmMenuRoles")
                        .HasForeignKey("MenuElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmMenuElement");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametrosSeleccion", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", "AdmParametroCategoria")
                        .WithMany("AdmParametrosSeleccions")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmParametroCategoria");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmReportsRole", b =>
                {
                    b.HasOne("PRAMS.Domain.Models.SystemConfiguration.AdmMenuRole", "AdmMenuRole")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmMenuRole");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmMenuElements", b =>
                {
                    b.Navigation("AdmMenuChildElements");

                    b.Navigation("AdmMenuRoles");
                });

            modelBuilder.Entity("PRAMS.Domain.Models.SystemConfiguration.AdmParametroCategoria", b =>
                {
                    b.Navigation("AdmParametrosSeleccions");
                });
#pragma warning restore 612, 618
        }
    }
}
